### ISSUE TITLE
Debug/Release sections that are probably covered by Sdk are left in project file

### ISSUE THREAD

**Issue by mungojam** [hvanbakel/CsprojToVs2017#113]
I expect all or most of these sections that are left in come through as default from the Sdk in the project format. I haven't looked into it much yet though. I don't know if I'm going to pick this up in a PR or not. I'd like to as it would clean up the converted projects a lot.

The only thing I think we have changed from default is to switch on `<DocumentationFile>` but that could always be dealt with as a separate change.

```xml
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <DocumentationFile>bin\Debug\OurAssembly.xml</DocumentationFile>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <DocumentationFile>bin\Release\OurAssembly.xml</DocumentationFile>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x86' ">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\x86\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <DebugType>full</DebugType>
    <PlatformTarget>x86</PlatformTarget>
    <CodeAnalysisUseTypeNameInSuppression>true</CodeAnalysisUseTypeNameInSuppression>
    <CodeAnalysisModuleSuppressionsFile>GlobalSuppressions.cs</CodeAnalysisModuleSuppressionsFile>
    <ErrorReport>prompt</ErrorReport>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x86' ">
    <OutputPath>bin\x86\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
    <DebugType>pdbonly</DebugType>
    <PlatformTarget>x86</PlatformTarget>
    <CodeAnalysisRuleAssemblies>
    </CodeAnalysisRuleAssemblies>
    <CodeAnalysisUseTypeNameInSuppression>true</CodeAnalysisUseTypeNameInSuppression>
    <CodeAnalysisModuleSuppressionsFile>GlobalSuppressions.cs</CodeAnalysisModuleSuppressionsFile>
    <ErrorReport>prompt</ErrorReport>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
    <CodeAnalysisIgnoreBuiltInRules>true</CodeAnalysisIgnoreBuiltInRules>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x64' ">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\x64\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <DebugType>full</DebugType>
    <PlatformTarget>x64</PlatformTarget>
    <CodeAnalysisRuleAssemblies>
    </CodeAnalysisRuleAssemblies>
    <CodeAnalysisUseTypeNameInSuppression>true</CodeAnalysisUseTypeNameInSuppression>
    <CodeAnalysisModuleSuppressionsFile>GlobalSuppressions.cs</CodeAnalysisModuleSuppressionsFile>
    <ErrorReport>prompt</ErrorReport>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
    <CodeAnalysisIgnoreBuiltInRules>true</CodeAnalysisIgnoreBuiltInRules>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x64' ">
    <OutputPath>bin\x64\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
    <DebugType>pdbonly</DebugType>
    <PlatformTarget>x64</PlatformTarget>
    <CodeAnalysisRuleAssemblies>
    </CodeAnalysisRuleAssemblies>
    <CodeAnalysisUseTypeNameInSuppression>true</CodeAnalysisUseTypeNameInSuppression>
    <CodeAnalysisModuleSuppressionsFile>GlobalSuppressions.cs</CodeAnalysisModuleSuppressionsFile>
    <ErrorReport>prompt</ErrorReport>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
    <CodeAnalysisIgnoreBuiltInRules>true</CodeAnalysisIgnoreBuiltInRules>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
```

**Comment by hvanbakel** [comment]
So far I’ve not touched this as I wanted to be on the safe side of things. There are probably a couple of these that can be gutted straight away, I just don’t know if things like `DebugType` actually still do something. I would hate to break things like that especially because they’re not obvious if you look at the converted project.

**Comment by mungojam** [comment]
Yeah, that's understandable. For now I've just added a custom transform that sets the whole additional property groups to null. That will work for 95% of our projects but I understand why that can't be the default.

My thought for a generic fix would be to dig out exactly what is in the new Sdk package as that should list all of the properties that actually come through from that. I don't think I'll get to do that myself. Maybe it's something that will just have to wait for the official converter. Yours does makes a compatible file and that's what matters to most users.

**Comment by mungojam** [comment]
Sounds like it's fixed by https://github.com/hvanbakel/CsprojToVs2017/pull/136. Haven't tried it myself but PR looks to cover it. I'll raise specific cases if I come across any that still look like they could be removed.

**Comment by mungojam** [comment]
Re-opening until #136 is merged, sorry hadn't spotted that

**Comment by andrew-boyarshin** [comment]
There is certainly a room for improvement.
* Only $(Platform) is used for replacement, and only in OutputPath (for some god-forsaken reason I didn't do the same to $(Configuration) and IntermediatePath, will do later)
* MSBuild evaluator is perfect, but its usage is not. Currently code assumes the conditionals do not contain anything other than atomic comparisons chained by `and`, `not` and `or` will certainly confuse things and will lead to wrong behavior (although the use of them is rare to say the least, 90% of all conditions contain only one atomic comparison that is a kind of `'$(Configuration)|$(Platform)'=='Conf|Plat'`)
* I am sure there are other properties I missed (although I covered the most frequently used). The examples could be CodeAnalysis* (never having used these myself).

Although it certainly is a big step forward and will introduce misconversion only in 1% of the cases. A good idea would be to introduce safeguards from `or` and additional command-line switch to skip simplification. Not in #136 though. I am working on diagnostics and analysis (you know, like usage of _Microsoft.CSharp_ or _System.Data.DataSetExtensions_ as assembly references instead of NuGet packages, too complex conditionals, unsupported Xamarin scenarios, etc.). Will even likely do HTML reports (Razor).

**Comment by mungojam** [comment]
Sounds ace, but what you've done is brill as it sounds like it covers the default project format that 99% of devs will have including at my company. We've very rarely tweaked the project file manually until the new format came along.

**Comment by hvanbakel** [comment]
I think we can close this one now that the PR is merged. Great work @andrew-boyarshin 👍
