### ISSUE TITLE
Configuration conditions

### ISSUE THREAD

**Issue by timmkrause** [hvanbakel/CsprojToVs2017#219]
Disclaimer: I am not that deep within the technical details, so please bear with me

I just realized that the tool generates

`<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">`

but according to [the official documentation](https://github.com/dotnet/project-system/blob/master/docs/configurations.md) this is kind of obsolete or do I misunderstand this in any way?

2nd question: Is `<Optimize>true</Optimize>` present by default somehow for `Release` configuration builds?

**Comment by andrew-boyarshin** [comment]
The tool really simplifies the project file, but does it in a safe way, simplifying away only the properties set to default in new CPS. The tool also removes empty `ProjectGroup`s, so this tool is completely compatible with both pre-15.3 and post-15.3 CPS. If you have an example of converted `.csproj` that contains entries you consider unnecessary in CPS, please, post it here so that we could verify tool's behavior and/or explain why they were left untouched.
2. It should be optimized away. If it is being left untouched - it's likely a bug and should be reported with more details.

**Comment by hvanbakel** [comment]
Closing this due to lack of details
