### ISSUE TITLE
Remove <Service Include="{82A7F48D-3B50-4B1E-B82E-3ADA8210C358}" />

### ISSUE THREAD

**Issue by leotsarev** [hvanbakel/CsprojToVs2017#229]
Per https://github.com/Microsoft/vstest/issues/472 its no need for this line in sdk-based csproj, at least if you are using:
- NUnit
- xunit

**Comment by hvanbakel** [comment]
Removing this everywhere, I tested with an MSTest project and it seemed to work just fine without it.

**Comment by andrew-boyarshin** [comment]
@hvanbakel I have to disagree with your fix. Service is included automatically by NUnit and xunit, but it is *test provider*-side fix. If user doesn't use NUnit or xunit, they still need this for VS 15.6 or earlier. I'd make it modernization transform instead, but keep it also here, just add NUnit or xunit package reference detection. That would be much safer.

**Comment by hvanbakel** [comment]
from reading that other issue it seemed like this was fixed in 15.3 reintroduced in 15.6 and then fixed properly in 15.7.

I am running 15.7 which is probably why I could run anything without any issues. It's an interesting case that you bring up though, what if users are on 15.5 still do we want to support that as well? I'm inclined to say no and work with latest minor. Thoughts?

**Comment by andrew-boyarshin** [comment]
I believe that, since we use "2017" in the title, we should target (or at least, try targetting) lowest possible 2017 version, that is, 15.0.
From my understanding of the issue, they first fixed it in most popular NuGet test providers, then tried multiple times fixing it in VS and only 15.7' attempt was final.
I still consider it a more advanced solution to be a combination of conditional (property simplification) and unconditional (modernization) transforms to reflect the possibility of this being a breaking change.

**Comment by hvanbakel** [comment]
I'll see if I can incorporate that later

**Comment by hvanbakel** [comment]
This was fixed by @andrew-boyarshin last night 👍  in 46a54521a33fd9b811f65e9fb4707bce182e76c7
