### ISSUE TITLE
<COMReference> are lost during transformation

### ISSUE THREAD

**Issue by diepe28** [hvanbakel/CsprojToVs2017#279]
Hello, 

I noticed that the <COMReference> elements are being lost during the transformation of a .csproj. Is there a design reason why this is happening? ComReferences are still used nowadays and are supported in the new .csproj format. Even though we would want to have pure .NET code, sometimes it is not possible. 

I debugged the code and realized that just by adding the entry "COMReference" to this field
IReadOnlyCollection<string> ItemsToProjectAlways, on the FileTransformation class, the COMReferences are migrated correctly and all unit tests are still passing.

Please let me know if there is a reason why these elements are not supported or if I can help out creating a pull request or something.

Thanks in advance.

**Comment by mungojam** [comment]
Hi, thanks for reporting this. I don't personally know any reason why we shouldn't migrate them, so go for it with the pull request. If you can add a failing unit test first so that you know you have implemented it correctly, that would be great, but I guess the current tests aren't covering everything.

**Comment by diepe28** [comment]
Great. 

I have created the Pull Request with the unit test.

**Comment by hvanbakel** [comment]
Closed via #280
